---
title: Language, Cognition and the Brain
output: html_document

---
<link rel="stylesheet" type="text/css" href="styles/main.css">
<link rel="stylesheet" type="text/css" href="styles/split-page.css">
<link rel="stylesheet" type="text/css" href="styles/textfolding.css">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to the course website!

<button type="button" class="collapsible">
Week 36: Introduction
</button>
<div class="content">

### Lecture and Discussion:

- The structure of the course
- The relationship between linguistic, cognitive, and neural processes
- Questions and answers


### Lab:

- Participate in an in-class experiment

### Assignment:

- Read:
  - Kemmerer chapter 1 pp. 3-10
  - Kemmerer chapter 3


</div>
<p></p><p></p>



<button type="button" class="collapsible">
Week 37: Aphasia 1
</button>
<div class="content">



### Lecture and Discusion:

- Classic aphasia syndromes
- Building a cognitive model from aphasia data

### Lab:

- Look at our data together

### Assignment:

- Read: 
  - Kemmerer chapter 1 pp. 10-20
  - Kemmerer chapter 4


</div>
<p></p><p></p>





<button type="button" class="collapsible">
Week 38: Aphasia 2
</button>
<div class="content">




### Lecture and Discusion:

- What is primary progressive aphasia?
- How can we use PPA to expand our neurocognitive model of language?

### Lab:

- 
- 

### Assignment:

- Read:
  - Kemmerer chapter 5 pp. 111-127
  - Kemmerer chapter 1 pp. 20-27


</div>
<p></p><p></p>




<button type="button" class="collapsible">
Week 39: Speech Perception 1
</button>
<div class="content">




### Lecture and Discusion:

- The dual-stream model of speech perception
- The early stages of speech perception

### Lab:

- 
- 

### Assignment:

- Read:
  - Kemmerer chapter 5 pp. 127-144

</div>
<p></p><p></p>




<button type="button" class="collapsible">
Week 40: Speech Perception 2
</button>
<div class="content">




### Lecture and Discusion:

- More detail on the dual stream model
- Auditory short-term memory
- Cortical organization of language


### Lab:

- 
- 

### Assignment:

- Read 
  - Kemmerer chapter 6 pp. 145-168


</div>
<p></p><p></p>




<button type="button" class="collapsible">
Week 41: Speech Production
</button>
<div class="content">




### Lecture and Discusion:

- Levelt's model of speech production

### Lab:

- 
- 

### Assignment:

- Read 
  - Kemmerer chapter 7

</div>
<p></p><p></p>




<button type="button" class="collapsible" style="background-color: #feb24c">
Week 42: Autumn Break <span style="font-size:32px">&#127810;</span>
</button>
<div class="content">


### Assignment:

- Relax


</div>
<p></p><p></p>





<button type="button" class="collapsible">
Week 43: Prosody
</button>
<div class="content">




### Lecture and Discusion:

- The perception of prosody
- The production of prosody
- Differences between emotional and linguistic prosody


### Lab:

- 
- 

### Assignment:

- Read 
  - Kemmerer chapter 10 pp 273-29
  - <a href="https://drive.google.com/file/d/18-jl_faBNcJgHI6v2rIm05VA8pSelTC3/view" target="_blank">Lambdon Ralph et al (2010)</a>

</div>
<p></p><p></p>




<button type="button" class="collapsible">
Week 44: Models of Concrete Noun Representation
</button>
<div class="content">




### Lecture and Discusion:

- Models of object noun representation
- The concept of “features”


### Lab:

- 
- 

### Assignment:

- Read 
  - Kemmerer chapter 11 pp 309-324

</div>
<p></p><p></p>


<button type="button" class="collapsible">
Week 45: Models of Action Verb Representation
</button>
<div class="content">




### Lecture and Discusion:

- Grounded cognition for action verbs
- The hub-and-spoke model for action verbs


### Lab:

- 
- 

### Assignment:

- Read TBA


</div>
<p></p><p></p>



<button type="button" class="collapsible">
Week 46: TBA - visit to brain museum?
</button>
<div class="content">




### Lecture and Discusion:

- 
- 

### Lab:

- 
- 

### Assignment:

- Read
  - Kemmerer: chapter 8 pp 215-230 (I might change this...)


</div>
<p></p><p></p>



<button type="button" class="collapsible">
Week 47: Reading and Dyslexia 1
</button>
<div class="content">




### Lecture and Discusion:

- Cognitive models of reading
- Neurocognitive models of reading

### Lab:

- 
- 

### Assignment:

- Read
  - Kemmerer chapter 8 pp 230-243
  - <a href="http://www.mdpi.com/2076-3425/8/4/61" target="_blank">  Protopapas and Parrila (2018)  </a>


</div>
<p></p><p></p>





<button type="button" class="collapsible">
Week 48: Reading and Dyslexia 2
</button>
<div class="content">




### Lecture and Discusion:

- Developmental Dyslexia
- Adult Dyslexia

### Lab:

- 
- 

### Assignment:

- Read
  - Cummings chapter 3


</div>
<p></p><p></p>




<button type="button" class="collapsible">
Week 49: Pragmatics
</button>
<div class="content">




### Lecture and Discusion:

- Pragmatic Disorders
- Right Hemisphere Disorder

### Lab:

- 
- 

### Assignment:

- Read
  - McGregor: Guide to structuring written and oral presentations
  - TBA

</div>
<p></p><p></p>



<button type="button" class="collapsible">
Week 50: Paper-writing workshop
</button>
<div class="content">

### Assignment:

- We work together to get our papers written!


</div>
<p></p><p></p>

<a href="https://drive.google.com/drive/folders/17L17p8vd6Sf9uQwUy4tk5dHBicCNR1T5?usp=sharing" target="_blank"> Slides </a>

<a href="https://ethanweed.github.io/teaching/Recommendations.html" target="_blank">Recommended Textbooks and Software</a>

  </div>
</div>

<script src="styles/textfolding.js"></script>

